"""Generate the public tool reference, ``docs/tools.md``, from the tool registry.

Every tool of every toolset, with its tier, description and parameters as MCP clients
see them, the fields of the nested input types (``ContractSpec``, ``OrderSpec``...), and
the service method behind each tool for library users. (``docs/coverage.md``, the TWS
API coverage table, is edited by hand; ``tests/unit/test_docs.py`` checks that it names
every tool.)

Usage::

    uv run python scripts/gen_docs.py            # write docs/tools.md
    uv run python scripts/gen_docs.py --check    # exit 1 if it is out of date

``tests/unit/test_docs.py`` fails when ``docs/tools.md`` no longer matches the registry.
"""

from __future__ import annotations

import argparse
import asyncio
import inspect
import re
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from ib_gateway_mcp.config import PROFILES, STREAMING_TOOLSETS, Settings
from ib_gateway_mcp.mcp.registry import REGISTRY, Tier
from ib_gateway_mcp.mcp.server import build_server

ROOT = Path(__file__).resolve().parent.parent
TOOLS_MD = ROOT / "docs" / "tools.md"
COVERAGE_MD = ROOT / "docs" / "coverage.md"

TOOLSET_ORDER = (
    "ops",
    "contracts",
    "market_data",
    "history",
    "scanners",
    "news",
    "fundamentals",
    "account",
    "options",
    "orders",
    "advisor",
    "admin",
)
TOOLSET_SUMMARIES = {
    "ops": "Gateway health, server time, connection details, accounts in scope. Always on.",
    "contracts": "Symbol search, contract details and qualification, option chains, "
    "market rules, SMART components, depth exchanges.",
    "market_data": "Quote snapshots, the market data type, and streaming quotes, depth, "
    "tick-by-tick data and bars; the generic subscription tools serve every stream.",
    "history": "Historical bars and ticks, head timestamps, histograms, trading schedules.",
    "scanners": "The scanner catalogue, one-shot scans and live scanner subscriptions.",
    "news": "News providers, historical headlines, articles, bulletins and live headlines.",
    "fundamentals": "Refinitiv fundamentals reports and Wall Street Horizon events.",
    "account": "Account summary and values, positions, portfolio, P&L, executions, "
    "open and completed orders.",
    "options": "IBKR's option calculators and quotes for a slice of an option chain.",
    "orders": "Previews (what-if) with single-use tokens, submit, cancel and status.",
    "advisor": "Financial advisor configuration, soft dollar tiers and family codes.",
    "admin": "The order circuit breaker, display groups and the gateway's API log level.",
}
TIER_LABELS = {
    Tier.READ: "read-only",
    Tier.WRITE: "write (changes state at IBKR; passes the [trading gate](#trading-gate) first)",
    Tier.ADMIN: "admin (changes gateway or server state; passes the [trading gate]"
    "(#trading-gate) first)",
}
SESSION_LABEL = "session (changes state every client of this server shares, not the account)"
TRADING_GATE = (
    "The **trading gate** runs before every write and admin tool. It passes only while the "
    "gateway is connected, a write toolset (orders, advisor or admin) is enabled, the "
    "login's accounts are known and one of them is allowed, no live account is in scope "
    "unless `IBKR_MCP_ALLOW_LIVE=true`, and the gateway's API is not in read-only mode. "
    "Orders then also pass the safety rails described in the README."
)
GENERATED = "<!-- Generated by scripts/gen_docs.py; do not edit by hand. -->"


_SERVICE_CALL = re.compile(r"\.(" + "|".join(TOOLSET_ORDER) + r")\.([a-z_]+)\(")
"""A call on a service in a tool body, e.g. ``gateway_from(ctx).orders.submit(``."""


def _library_call(spec: Any) -> str:
    """The service method a tool wraps: the last service call in its body."""
    calls = _SERVICE_CALL.findall(inspect.getsource(inspect.unwrap(spec.fn)))
    if not calls:
        raise SystemExit(f"{spec.name}: no service call found in the tool body")
    service, method = calls[-1]
    return f"`gw.{service}.{method}()`"


def _tier_label(spec: Any) -> str:
    if spec.tier is Tier.READ and spec.annotations.read_only_hint is False:
        return SESSION_LABEL
    return TIER_LABELS[spec.tier]


# --- tools.md --------------------------------------------------------------------------------


def _cell(text: str) -> str:
    """Make ``text`` safe inside a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def _type_anchor(name: str) -> str:
    return f"type-{name.lower()}"


def _type_of(schema: Mapping[str, Any]) -> str:  # noqa: PLR0911 (one case per schema form)
    """A short type name for a JSON schema fragment; nested types link to their fields."""
    if "$ref" in schema:
        name = str(schema["$ref"]).rsplit("/", 1)[-1]
        return f"[{name}](#{_type_anchor(name)})"
    if "enum" in schema:
        return " | ".join(repr(value).replace("'", '"') for value in schema["enum"])
    if "const" in schema:
        return repr(schema["const"]).replace("'", '"')
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts = [_type_of(part) for part in schema[key]]
            return " | ".join(dict.fromkeys(parts))
    kind = schema.get("type")
    if kind == "array":
        return f"list[{_type_of(schema.get('items', {}))}]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        return f"dict[str, {_type_of(extra)}]" if isinstance(extra, dict) else "object"
    if isinstance(kind, list):
        return " | ".join(str(k) for k in kind)
    return str(kind or "any")


def _default(schema: Mapping[str, Any]) -> str:
    if "default" not in schema:
        return ""
    value = schema["default"]
    if value is None:
        return "null"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return f'"{value}"'
    return _cell(repr(value))


def _parameters(input_schema: Mapping[str, Any], heading: str = "Parameter") -> list[str]:
    properties: Mapping[str, Any] = input_schema.get("properties", {})
    if not properties:
        return ["No parameters."]
    required = set(input_schema.get("required", []))
    lines = [
        f"| {heading} | Type | Required | Default | Description |",
        "|---|---|---|---|---|",
    ]
    for name, schema in properties.items():
        lines.append(
            f"| `{name}` | {_cell(_type_of(schema))} | {'yes' if name in required else 'no'} "
            f"| {_default(schema)} | {_cell(str(schema.get('description', '')))} |"
        )
    return lines


def _description(text: str) -> list[str]:
    """The tool docstring as Markdown: paragraphs, and lists set off by blank lines."""
    out: list[str] = []
    in_list = False
    for raw in inspect.cleandoc(text).splitlines():
        content = raw.strip()
        if content.startswith("- "):
            if not in_list and out and out[-1]:
                out.append("")
            in_list = True
            out.append(content)
        elif in_list and content and raw[:1].isspace():
            out.append("  " + content)  # continuation of the list item
        else:
            if in_list and content:
                out.append("")
            in_list = False
            out.append(content)
    return out


def _input_types(tools: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    """The nested input types (JSON schema ``$defs``) of every tool, by name."""
    types: dict[str, Mapping[str, Any]] = {}
    for tool in tools.values():
        for name, schema in tool.input_schema.get("$defs", {}).items():
            if types.setdefault(name, schema) != schema:
                raise SystemExit(f"two different input types are both named {name}")
    return dict(sorted(types.items()))


def _types_section(types: Mapping[str, Mapping[str, Any]]) -> list[str]:
    lines = [
        "",
        '<a id="types"></a>',
        "",
        "## Types",
        "",
        "The nested objects that tool parameters take, with their fields. Unknown fields "
        "are rejected.",
    ]
    for name, schema in types.items():
        description = str(schema.get("description", "")).replace("``", "`")
        lines += [
            "",
            f'<a id="{_type_anchor(name)}"></a>',
            "",
            f"### {name}",
            "",
            *(_description(description) if description else []),
            "",
            *_parameters(schema, heading="Field"),
        ]
    return lines


def _profiles_of(toolset: str) -> list[str]:
    return [name for name, sets in PROFILES.items() if toolset in sets]


async def _tool_schemas() -> dict[str, Any]:
    # Building the server connects nowhere; only the tool list is read.
    server = build_server(Settings(profile="full", toolsets=None, transport="stdio"))
    return {tool.name: tool for tool in await server.list_tools()}


def render_tools() -> str:
    """The contents of ``docs/tools.md``."""
    tools = asyncio.run(_tool_schemas())
    specs = {spec.name: spec for spec in REGISTRY.specs()}
    by_toolset: dict[str, list[str]] = {}
    for spec in specs.values():
        by_toolset.setdefault(spec.toolset, []).append(spec.name)
    counts = {
        name: sum(len(by_toolset.get(toolset, [])) for toolset in sets)
        for name, sets in PROFILES.items()
    }
    lines = [
        "# Tools",
        "",
        GENERATED,
        "",
        f"{len(specs)} tools in {len(by_toolset)} toolsets. A profile "
        "(`IBKR_MCP_PROFILE`) or an explicit list (`IBKR_MCP_TOOLSETS`) decides which are "
        "registered: " + ", ".join(f"`{name}` {count}" for name, count in counts.items()) + ".",
        "`ops` is always on; "
        + ", ".join(f"`{name}`" for name in sorted(STREAMING_TOOLSETS))
        + " also turn on `market_data`, whose subscription tools read and cancel their streams.",
        "Nested parameter types are described under [Types](#types).",
        "",
        '<a id="trading-gate"></a>',
        TRADING_GATE,
        "",
        "| Toolset | Profiles | Tools |",
        "|---|---|---|",
    ]
    for toolset in TOOLSET_ORDER:
        names = ", ".join(f"[`{name}`](#{name})" for name in sorted(by_toolset[toolset]))
        profiles = ", ".join(_profiles_of(toolset)) or "via IBKR_MCP_TOOLSETS"
        lines.append(f"| [`{toolset}`](#toolset-{toolset}) | {profiles} | {names} |")
    for toolset in TOOLSET_ORDER:
        lines += [
            "",
            f'<a id="toolset-{toolset}"></a>',
            "",
            f"## {toolset}",
            "",
            TOOLSET_SUMMARIES[toolset],
        ]
        for name in sorted(by_toolset[toolset]):
            spec, tool = specs[name], tools[name]
            lines += [
                "",
                f"### {name}",
                "",
                f"**{spec.title}**: {_tier_label(spec)}. Library: {_library_call(spec)}.",
                "",
                *_description(tool.description or ""),
                "",
                *_parameters(tool.input_schema),
            ]
    lines += _types_section(_input_types(tools))
    return "\n".join(lines) + "\n"


# --- entry point -----------------------------------------------------------------------------


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"{path.relative_to(ROOT)} is out of date; run scripts/gen_docs.py", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if a file is out of date")
    args = parser.parse_args(list(argv) if argv is not None else None)
    ok = _write_or_check(TOOLS_MD, render_tools(), args.check)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
